/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as DarkroomPrintingRouteImport } from './routes/darkroom-printing'
import { Route as ExhibitionsAndWorksRouteImport } from './routes/exhibitions-and-works'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const DarkroomPrintingRoute = DarkroomPrintingRouteImport.update({
  id: '/darkroom-printing',
  path: '/darkroom-printing',
  getParentRoute: () => rootRouteImport,
} as any)
const ExhibitionsAndWorksRoute = ExhibitionsAndWorksRouteImport.update({
  id: '/exhibitions-and-works',
  path: '/exhibitions-and-works',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contacts': typeof ContactsRoute
  '/darkroom-printing': typeof DarkroomPrintingRoute
  '/exhibitions-and-works': typeof ExhibitionsAndWorksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contacts': typeof ContactsRoute
  '/darkroom-printing': typeof DarkroomPrintingRoute
  '/exhibitions-and-works': typeof ExhibitionsAndWorksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contacts': typeof ContactsRoute
  '/darkroom-printing': typeof DarkroomPrintingRoute
  '/exhibitions-and-works': typeof ExhibitionsAndWorksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/contacts' | '/darkroom-printing' | '/exhibitions-and-works'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/contacts' | '/darkroom-printing' | '/exhibitions-and-works'
  id:
    | '__root__'
    | '/'
    | '/contacts'
    | '/darkroom-printing'
    | '/exhibitions-and-works'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactsRoute: typeof ContactsRoute
  DarkroomPrintingRoute: typeof DarkroomPrintingRoute
  ExhibitionsAndWorksRoute: typeof ExhibitionsAndWorksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/darkroom-printing': {
      id: '/darkroom-printing'
      path: '/darkroom-printing'
      fullPath: '/darkroom-printing'
      preLoaderRoute: typeof DarkroomPrintingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exhibitions-and-works': {
      id: '/exhibitions-and-works'
      path: '/exhibitions-and-works'
      fullPath: '/exhibitions-and-works'
      preLoaderRoute: typeof ExhibitionsAndWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactsRoute: ContactsRoute,
  DarkroomPrintingRoute: DarkroomPrintingRoute,
  ExhibitionsAndWorksRoute: ExhibitionsAndWorksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
